Feature integration : want to add task remaining and task completed feature in task -input
Polaris-School-of-Technology/Personal-Management-Dashboard pull request #90
Opened 2024-12-16 11:49 UTC by RIYAKUMARI001

Description:
This PR introduces the ability to track the remaining tasks and tasks completed directly within the task input section, improving task management and visibility.

Context:
Users requested an intuitive way to see their progress when managing tasks. By displaying the count of tasks remaining and completed, this feature provides real-time updates and helps users stay organized and motivated.

Implementation:
Added a task counter that dynamically updates based on tasks added, completed, or removed.
Introduced two new UI elements:
Tasks Remaining: Displays the count of tasks that are not marked as completed.
Tasks Completed: Displays the count of tasks marked as completed.
Optimized DOM manipulation to ensure the counters update efficiently without performance lag.
Added tests to validate the correctness of task counting and display logic.

Testing:
Add multiple tasks and verify that the Tasks Remaining counter increases accordingly.
Mark tasks as completed and ensure the Tasks Completed counter updates while Tasks Remaining decreases.

Sample Video -
https://github.com/user-attachments/assets/33258660-df5d-4dbc-8bd8-227bcb7caccf

Adressing this issue #75

2024-12-16 16:00 UTC, rahat2134 commented
@RIYAKUMARI001, can you share a video using all the things locally in PMD(personal management dashboard)...
Will merge it then...

2024-12-16 16:20 UTC, rahat2134 requested changes
Gave a top level review for the changes. Mostly gave feedback on code quality and refactoring. Try to use indentation properly.

2024-12-16 16:20 UTC, rahat2134 commented on styles.css
> +  float: right;
remove this extra space

2024-12-16 16:20 UTC, rahat2134 commented on styles.css
> +
remove this extra space.

2024-12-16 16:20 UTC, rahat2134 commented on index.html
> -  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
why removing this?

2024-12-16 16:20 UTC, rahat2134 commented on index.html
> +      </div>
Keep the indentation properly.
Eg - 
```
      <div id = "task-input-container">
        <input type="text" id="task-input" placeholder="New Task">
        <button id="add-task-btn">Add Task</button>
      </div>
```

2024-12-16 16:20 UTC, rahat2134 commented on index.html
> +      </div>
Here also indentation is unsuitable.

2024-12-16 16:20 UTC, rahat2134 commented on index.html
> +      </div>
Here also indentation is unsuitable.

2024-12-16 16:20 UTC, rahat2134 commented on index.html
> -      <h2>Passwords</h2>
Why removing this?

2024-12-16 16:20 UTC, rahat2134 commented on script.js
> +    editButton.textContent = 'Edit';
Here also indentation is unsuitable.

Corrected - 
```
      newTask.classList.add('task-item');
      const checkbox = document.createElement('input');
      checkbox.type = 'checkbox';
      checkbox.classList.add('task-checkbox');
      const taskText = document.createElement('span');
      taskText.textContent = taskInput.value;
      const editButton = document.createElement('button');
      editButton.classList.add('editbtn');
      editButton.textContent = 'Edit';
```

i.e make it align to 
```
      const newTask =document.createElement('li');
```
indentation here.

Note - Make the indentation proper wherever you find.

2024-12-16 16:20 UTC, rahat2134 commented on script.js
> +     const completedTasks = document.querySelectorAll('#task-list input:checked');
indentation correct...

2024-12-16 16:20 UTC, rahat2134 commented on script.js
> +
remove this space.

2024-12-16 16:20 UTC, rahat2134 commented on styles.css
> +
only 1 space needed.

2024-12-16 16:20 UTC, rahat2134 commented on styles.css
> +
remove this extra line..

2024-12-16 16:20 UTC, rahat2134 commented on styles.css
> +
remove extra line.

2024-12-16 21:27 UTC, RIYAKUMARI001 commented
@rahat2134 I have made all the changes you suggested, Please review the PR and please let me know if any other changes needed.

https://github.com/user-attachments/assets/8f0e0554-31a9-4675-9b81-cbacc9f4605b

2024-12-16 21:28 UTC, RIYAKUMARI001 commented on styles.css
> +
okay.

2024-12-24 07:56 UTC, OpensourceMaverick requested changes
Gave a little more feedback on the PR, Please consider code refactoring. Please take a look to whole changes of your's I just gave feedback on initial changes.

2024-12-24 07:56 UTC, OpensourceMaverick commented on script.js
> +    updateTaskSummary();
Please review the code refactoring, Refactoring is needed!
``` javascript
newTask.classList.add('task-item');
const checkbox= document.createElement('input');
checkbox.type = 'checkbox';
checkbox.classList.add('task-checkbox');
const taskText= document.createElement('span');
taskText.textContent = taskInput.value;
const editButton = document.createElement('button');
editButton.classList.add('editbtn');
editButton.textContent = 'Edit';
const deleteButton = document.createElement('button');
deleteButton.classList.add('deletebtn');
deleteButton.textContent = 'Delete';
newTask.appendChild(checkbox);
newTask.appendChild(taskText);
newTask.appendChild(editButton);
newTask.appendChild(deleteButton);  
deletebtn(newTask); 
editbtn(newTask); 
taskList.appendChild(newTask);
taskInput.value = '';
updateTaskSummary();
```

2024-12-24 08:01 UTC, rahat2134 requested changes
Gave a little more feedback on the PR, Please consider code refactoring. Please take a look to whole changes of your's I just gave feedback on initial changes.

2024-12-24 08:01 UTC, rahat2134 commented on script.js
> +    updateTaskSummary();
Please review the code refactoring, Refactoring is needed!
``` javascript
newTask.classList.add('task-item');
const checkbox= document.createElement('input');
checkbox.type = 'checkbox';
checkbox.classList.add('task-checkbox');
const taskText= document.createElement('span');
taskText.textContent = taskInput.value;
const editButton = document.createElement('button');
editButton.classList.add('editbtn');
editButton.textContent = 'Edit';
const deleteButton = document.createElement('button');
deleteButton.classList.add('deletebtn');
deleteButton.textContent = 'Delete';
newTask.appendChild(checkbox);
newTask.appendChild(taskText);
newTask.appendChild(editButton);
newTask.appendChild(deleteButton);  
deletebtn(newTask); 
editbtn(newTask); 
taskList.appendChild(newTask);
taskInput.value = '';
updateTaskSummary();
```

2024-12-24 08:12 UTC, rahat2134 commented
do the changes, will merge the changes after reviews.

2024-12-25 14:44 UTC, RIYAKUMARI001 commented
> do the changes, will merge the changes after reviews.
okay i will make the changes acc to the suggestion

2024-12-25 14:48 UTC, RIYAKUMARI001 commented
I have made all the changes as you suggested,  please let me know if any further changes needed.
![Screenshot 2024-12-25 201501](https://github.com/user-attachments/assets/49796979-3eaf-4dbb-a62a-11c34ed522aa)

2025-07-08 19:37 UTC, closed without merging